/**
 * @author 	SC (<TRIGRAM>)
 * @version 1.0
 * @since	<LastModifiedDate>
 *
 * Describe here what the class do
 * 
 *-- Maintenance History: 
 *--
 *-- Date         Name  Version  Remarks 
 *-- -----------  ----  -------  -------------------------------------------------------
 *-- DD-MMM-YYYY  <TRIGRAM>    1.0     Initial version
 *--------------------------------------------------------------------------------------
 * 
 */
public with sharing class {{ api_name }} {

	public {{ api_name }}() {
		system.debug('## starting class constructor');
	}
}
