/**
 * @author 	SC (<TRIGRAM>)
 * @version 1.0
 * @since	<LastModifiedDate>
 *
 * Describe here what the class do
 * 
 *-- Maintenance History: 
 *--
 *-- Date         Name  Version  Remarks 
 *-- -----------  ----  -------  -------------------------------------------------------
 *-- DD-MMM-YYYY  <TRIGRAM>    1.0     Initial version
 *--------------------------------------------------------------------------------------
 * 
 */
public with sharing class {{ api_name }} {
	
	/**
     * This method do the following  :
     * 1. Initialise the ...
     * 2. ..........
     * 
     * @param  stdController	The standard controller to extends
     * @return none
     */	
	public {{ api_name }}(ApexPages.StandardController stdController) {
		system.debug('## starting class constructor');		
	}

}
